apiVersion: v1
kind: Secret
metadata:
  name: todo-api-config
type: Opaque
stringData:
  postgres-write: Host=postgres;Database=axes;Username=postgres;Password=replace-me
  postgres-read: Host=postgres;Database=axes;Username=postgres;Password=replace-me
  redis: redis:6379
  jwt-key: replace-with-the-same-local-key-used-by-orders
---
apiVersion: v1
kind: Secret
metadata:
  name: todo-orders-config
type: Opaque
stringData:
  postgres: Host=postgres;Database=axes;Username=postgres;Password=replace-me
  jwt-key: replace-with-the-same-local-key-used-by-api
  rabbitmq-username: guest
  rabbitmq-password: guest
---
apiVersion: v1
kind: Secret
metadata:
  name: todo-inventory-config
type: Opaque
stringData:
  postgres: Host=postgres;Database=axes;Username=postgres;Password=replace-me
  rabbitmq-username: guest
  rabbitmq-password: guest
