<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>CS0219</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNext" Version="6.6.0" />
    <PackageReference Include="DotNext.Threading" Version="6.6.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Labuladong\Classic\leetcode\editor\en\doc\content\" />
  </ItemGroup>
</Project>
